---
- name: Install required package to add qdevice on all cluster node
  apt:
    name: "{{ item }}"
    state: 'present'
  loop:
    - "{{ pacemaker_cluster_package }}"
    - "{{ pcs_module_dependencies }}"
  when: not cluster_node_is_arbiter

- name: Install required package on the qdevice
  apt:
    name: "{{ pacemaker_qdevice_package }}"
    state: 'present'
  when: cluster_node_is_arbiter
